Fixes issue #257 (intermittent failure to launch images due to ProcessWrapper causing error 998).
pharo-project/pharo-launcher pull request #329
Opened 2019-04-02 16:03 UTC by avasopht

Fix to: #257, replacing ProcessWrapper with a more robust wrapper for win32\CreateProcess.

Error 998 is a common symptom of uninitialized structs, which I suspect caused the issue with ProcessWrapper. This error stopped immediately after making this fix, and it's been working without any issue for 6 weeks.

2019-04-03 08:23 UTC, guillep requested changes
I like this change, I think it goes in a nice direction, and it would make making the 64bit launcher working more easily.

I have some comments on the PR however.

@demarey do we have tests on these things? It should not be complicated to write some basic tests on launching images... Otherwise this kind of change requires lots of manual testing...

2019-04-03 08:23 UTC, guillep commented on src/PharoLauncher-Process/PhLProcess.class.st
> +	cmd ifNotNil: [ cmdString := ExternalAddress fromString: cmd ].
This only works for ascii strings

2019-04-03 08:23 UTC, guillep commented on src/PharoLauncher-Process/PhLProcess.class.st
> +	^ self ffiCall: #(int CreateProcessA (const char * appName, char * command, 0, 0, 0, ulong flags, 0, 0, ExternalAddress * startup, ExternalAddress * processInfo)) module: #Kernel32
Any chance to make it work with CreateProcessW? If you check the package `System-Platforms-Windows` there are already some classes to do windows wide string marshalling

2019-04-03 08:23 UTC, guillep commented on src/PharoLauncher-Process/PhLProcess.class.st
> +
This file is really strange: it has all extension methods that should be in an extension file, and the extension file (`PhlProcess.extension.st`) is repeating all this code all over the place.

Did you use Iceberg to commit this (and did you select all changes)?

2019-04-04 00:12 UTC, avasopht commented on src/PharoLauncher-Process/PhLProcess.class.st
> +
Hi @guillep, I originally wrote those methods as an extension before moving them into PhLProcess. Seems I forgot to create the protocols. I'll update that.

2019-04-04 00:14 UTC, avasopht commented on src/PharoLauncher-Process/PhLProcess.class.st
> +	^ self ffiCall: #(int CreateProcessA (const char * appName, char * command, 0, 0, 0, ulong flags, 0, 0, ExternalAddress * startup, ExternalAddress * processInfo)) module: #Kernel32
Okay, I will add that in as well.

2019-04-08 14:16 UTC, demarey commented
Hi Keldon, 

Thanks for this pull request. It is true that the fork of processes on Windows is not reliable enough. Using Windows API looks to be the right way.

@guillep There are tests for image version determination using process forks: https://github.com/pharo-project/pharo-launcher/blob/development/src/PharoLauncher-Tests-Functional/PhLVirtualMachineManagerFunctionalTest.class.st#L42.
There are also a few tests on forkin processes:
https://github.com/pharo-project/pharo-launcher/blob/development/src/PharoLauncher-Tests-Functional/PhLProcessWrapperTest.class.st
But the point is that test are only checked Linux for now.

@avasopht It would be great if you could use the CreateProcessW function. We recently had issues because of the encoding. For example, in french, non-ASCII characters are frequent in names, so you can easily find non-ASCII characters for the HOME directory, part of the path to images and vms.

2019-04-08 14:17 UTC, demarey commented on src/PharoLauncher-Core/PhLProcessWrapper.class.st
> +			ifTrue: [ self windowsCommand: encodedCommand ]
should'nt it be self waitForWindowsCommand: here?

2019-06-26 08:02 UTC, demarey commented
@avasopht Thanks a lot for this PR. It gave me the opportunity to dive a bit in Windows process creation and take time to package a library that works on the Unicode API and having a similar API as OSSubprocess: https://github.com/pharo-contributions/OSWinSubprocess. If it is ok for you, I will close this PR. Pharo Launcher will use this library if feedbacks are good. There is still work to do on this library but it is a good start.

2019-06-28 00:50 UTC, avasopht commented
> @avasopht Thanks a lot for this PR. It gave me the opportunity to dive a bit in Windows process creation and take time to package a library that works on the Unicode API and having a similar API as OSSubprocess: https://github.com/pharo-contributions/OSWinSubprocess. If it is ok for you, I will close this PR. Pharo Launcher will use this library if feedbacks are good. There is still work to do on this library but it is a good start.
> 
> > <img alt="" width="48" src="https://avatars1.githubusercontent.com/u/29709313?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/4908d9947135e4536ef61d61512ee575f869bf6f/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e2e69636f"> GitHub**[pharo-contributions/OSWinSubprocess](https://github.com/pharo-contributions/OSWinSubprocess)**Forking Windows System Processes from within Pharo Language  - pharo-contributions/OSWinSubprocess

Brilliant!

2019-07-05 13:44 UTC, closed without merging